<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EtablissementsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('etablissements')->insert([
            [
                'id' => 1,
                'nom_etablissement' => 'Centre Hospitalier Universitaire de Libreville',
                'code_etablissement' => 'LBV-01',
                'raison_sociale' => '356 Rue Ndende, Libreville',
                'statut_juridique' => 'Entreprise Public',
                'site_web' => '',
                'tel' => '011 72 32 15',
                'bp' => '',
                'logo' => 'assets\images\etablissement\hopital\chul.jpg',
                'ville_id' => 1,
                'type_etablissement_id' => 1,
            ],
            [
                'id' => 2,
                'nom_etablissement' => 'Hôpital d’Instruction des Armées OBO',
                'code_etablissement' => 'LBV-02',
                'raison_sociale' => 'CG44+P3V, Libreville',
                'statut_juridique' => 'Entreprise Public',
                'site_web' => '',
                'tel' => '011 79 00 00',
                'bp' => '',
                'logo' => '\assets\images\etablissement\hopital\hia.jpg',
                'ville_id' => 1,
                'type_etablissement_id' => 4,
            ],
            [
                'id' => 3,
                'nom_etablissement' => 'Centre Hospitalier Universitaire d’Angondjé',
                'code_etablissement' => 'LBV-03',
                'raison_sociale' => 'GC93+9QJ, Libreville',
                'statut_juridique' => 'Entreprise Public',
                'site_web' => '',
                'tel' => '011 79 00 00',
                'bp' => '',
                'logo' => '\assets\images\etablissement\hopital\chua.jpg',
                'ville_id' => 1,
                'type_etablissement_id' => 1,
            ],
            [
                'id' => 4,
                'nom_etablissement' => 'Centre de Santé Egypto-Gabonais',
                'code_etablissement' => 'LBV-04',
                'raison_sociale' => 'Libreville',
                'statut_juridique' => 'Entreprise Privé',
                'site_web' => '',
                'tel' => '011 76 18 13',
                'bp' => '',
                'logo' => '\assets\images\etablissement\hopital\hceg.jpg',
                'ville_id' => 1,
                'type_etablissement_id' => 1,
            ],
            [
                'id' => 5,
                'nom_etablissement' => 'Centre Hospitalier Universitaire Owendo',
                'code_etablissement' => 'OWO-01',
                'raison_sociale' => 'Libreville',
                'statut_juridique' => 'Entreprise Privé',
                'site_web' => '',
                'tel' => '062 52 03 80',
                'bp' => '',
                'logo' => '\assets\images\etablissement\hopital\chuo.jpg',
                'ville_id' => 1,
                'type_etablissement_id' => 1,
            ],
            [
                'id' => 6,
                'nom_etablissement' => 'Centre Hospitalier Régional Amissa BONGO',
                'code_etablissement' => 'FRA-01',
                'raison_sociale' => 'Mpassa',
                'statut_juridique' => 'Entreprise Publique',
                'site_web' => '',
                'tel' => '011 67 72 82',
                'bp' => '',
                'logo' => '\assets\images\etablissement\hopital\chra.jpg',
                'ville_id' => 2,
                'type_etablissement_id' => 2,
            ],
            [
                'id' => 7,
                'nom_etablissement' => 'Hôpital Albert SCHWEITZER',
                'code_etablissement' => 'LAM-01',
                'raison_sociale' => 'N1, Lambarene',
                'statut_juridique' => 'Entreprise Publique',
                'site_web' => '',
                'tel' => '',
                'bp' => '',
                'logo' => 'assets\images\etablissement\hopital\hasl.jpg',
                'ville_id' => 3,
                'type_etablissement_id' => 4,
            ],
            [
                'id' => 8,
                'nom_etablissement' => 'Centre Hospitalier Régional de Mouila',
                'code_etablissement' => 'MOU-01',
                'raison_sociale' => '2GW+V38, Mouila',
                'statut_juridique' => 'Entreprise Publique',
                'site_web' => '',
                'tel' => '',
                'bp' => '',
                'logo' => '\assets\images\etablissement\hopital\chrm.jpg',
                'ville_id' => 4,
                'type_etablissement_id' => 2,
            ],
            [
                'id' => 9,
                'nom_etablissement' => 'Centre Hospitalier  Régional Benjamin NGOUBOU',
                'code_etablissement' => 'TCH-01',
                'raison_sociale' => 'Tchibanga',
                'statut_juridique' => 'Entreprise Publique',
                'site_web' => '',
                'tel' => '',
                'bp' => '',
                'logo' => '\assets\images\etablissement\hopital\chrt.jpg',
                'ville_id' => 5,
                'type_etablissement_id' => 2,
            ],
            [
                'id' => 10,
                'nom_etablissement' => 'Centre Hospitalier Régional Paul MOUKAMBI',
                'code_etablissement' => 'KOU-01',
                'raison_sociale' => 'BP 03, Koulamoutou',
                'statut_juridique' => 'Entreprise Publique',
                'site_web' => '',
                'tel' => '077 01 67 00',
                'bp' => '03',
                'logo' => '\assets\images\etablissement\hopital\chrk.jpg',
                'ville_id' => 5,
                'type_etablissement_id' => 2,
            ],
            [
                'id' => 11,
                'nom_etablissement' => 'Centre Hospitalier Régional de Tchengue',
                'code_etablissement' => 'POR-01',
                'raison_sociale' => 'Hôpital NTchengue, Boulevard, Port-Gentil',
                'statut_juridique' => 'Entreprise Publique',
                'site_web' => '',
                'tel' => '',
                'bp' => '1232',
                'logo' => '\assets\images\etablissement\hopital\chrp.jpg',
                'ville_id' => 8,
                'type_etablissement_id' => 2,
            ],
        ]);
    }
}
