<?php

use App\Medicament;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class MedicamentsTableSeeder extends Seeder
{
    private $medicamentData = [];

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('medicaments')->insert([ 
            [
                'id' => 1,
                'nom_commercial' => 'THERALENE',
                'dci' => 'ALIMEMAZINE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 2,
                'nom_commercial' => 'CELESTAMINE',
                'dci' => 'BETAMETHASONE + DEXCHLORPHENIRAMINE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 3,
                'nom_commercial' => 'TAREG',
                'dci' => 'VALSARTAN', 
                'taux_rem' => 0.5,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 4,
                'nom_commercial' => 'BILAXTEN',
                'dci' => 'BILASTINE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 5,
                'nom_commercial' => 'CURTEC',
                'dci' => 'CETIRIZINE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 6,
                'nom_commercial' => 'VIRLIX',
                'dci' => 'CETIRIZINE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 7,
                'nom_commercial' => 'ZYRTEC',
                'dci' => 'CETIRIZINE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 8,
                'nom_commercial' => 'AERIUS',
                'dci' => 'DESLORATADINE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 9,
                'nom_commercial' => 'DESLOR',
                'dci' => 'DESLORATADINE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 10,
                'nom_commercial' => 'POLARAMINE',
                'dci' => 'DEXCHLORPHENIRAMINE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 11,
                'nom_commercial' => 'NAUTAMINE',
                'dci' => 'DIPHENHYDRAMINE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 12,
                'nom_commercial' => 'XYZALL',
                'dci' => 'LEVOCETIRIZINE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 13,
                'nom_commercial' => 'BILOR',
                'dci' => 'LORATADINE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 14,
                'nom_commercial' => 'LORIX',
                'dci' => 'LORATADINE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 15,
                'nom_commercial' => 'LORATOL',
                'dci' => 'LORATADINE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 16,
                'nom_commercial' => 'TIRLOR',
                'dci' => 'LORATADINE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 17,
                'nom_commercial' => 'ZIFAR',
                'dci' => 'LORATADINE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 18,
                'nom_commercial' => 'CLARITYNE',
                'dci' => 'LORATADINE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 19,
                'nom_commercial' => 'PRIMALAN',
                'dci' => 'MEQUITAZINE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 20,
                'nom_commercial' => 'PHENERGAN',
                'dci' => 'PROMETHAZINE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 21,
                'nom_commercial' => 'RINIALER',
                'dci' => 'RUPATADINE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 22,
                'nom_commercial' => 'ASPEGIC',
                'dci' => 'ACETYLSALICYLATE DE LYSINE', 
                'taux_rem' => 0.5,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 23,
                'nom_commercial' => 'ASPIRINE PH 8',
                'dci' => 'ACETYLSALICYLATE DE LYSINE', 
                'taux_rem' => 0.5,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 24,
                'nom_commercial' => 'ANTIDOL',
                'dci' => 'PARACETAMOL', 
                'taux_rem' => 0.5,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 25,
                'nom_commercial' => 'DOLIPRANE',
                'dci' => 'PARACETAMOL', 
                'taux_rem' => 0.5,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 26,
                'nom_commercial' => 'DOLKO',
                'dci' => 'PARACETAMOL', 
                'taux_rem' => 0.5,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 27,
                'nom_commercial' => 'EFFERALGAN',
                'dci' => 'PARACETAMOL', 
                'taux_rem' => 0.5,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 28,
                'nom_commercial' => 'PANADOL',
                'dci' => 'PARACETAMOL', 
                'taux_rem' => 0.5,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 29,
                'nom_commercial' => 'PARACETAMOL EG',
                'dci' => 'PARACETAMOL', 
                'taux_rem' => 0.5,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 30,
                'nom_commercial' => 'PARACETAMOL MACOPHARMA',
                'dci' => 'PARACETAMOL', 
                'taux_rem' => 0.5,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 31,
                'nom_commercial' => 'PERFALGAN',
                'dci' => 'PARACETAMOL', 
                'taux_rem' => 0.5,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 32,
                'nom_commercial' => 'PAROL',
                'dci' => 'PARACETAMOL', 
                'taux_rem' => 0.5,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 33,
                'nom_commercial' => 'PARACETAMOL',
                'dci' => 'PARACETAMOL', 
                'taux_rem' => 0.5,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 34,
                'nom_commercial' => 'PARA DENK',
                'dci' => 'PARACETAMOL', 
                'taux_rem' => 0.5,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 35,
                'nom_commercial' => 'DOLVIRAN',
                'dci' => 'ACIDE ACETYL SALICYLIQUE + CODEÏNE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 36,
                'nom_commercial' => 'ANTARENE CODEINE',
                'dci' => 'IBUPROFENE+ CODEÏNE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 37,
                'nom_commercial' => 'ACUPAN',
                'dci' => 'NEFOPAM', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 38,
                'nom_commercial' => 'ALFENAC',
                'dci' => 'PARACETAMOL + ACECLOFENAC', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 39,
                'nom_commercial' => 'PANADOL FEMINA',
                'dci' => 'PARACETAMOL + BUTHYLBROMURE DE HYOSCINE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 40,
                'nom_commercial' => 'ALGISEDAL',
                'dci' => 'PARACETAMOL + CODEINE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 41,
                'nom_commercial' => 'CO-DOLIPRANE',
                'dci' => 'PARACETAMOL + CODEINE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 42,
                'nom_commercial' => 'EFFERALGAN CODEINE',
                'dci' => 'PARACETAMOL + CODEINE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 43,
                'nom_commercial' => 'EKLIPAL CODEINE',
                'dci' => 'PARACETAMOL + CODEINE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 44,
                'nom_commercial' => 'PANADOL EXTRA',
                'dci' => 'PARACETAMOL + CAFEINE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 45,
                'nom_commercial' => 'PANALGIC',
                'dci' => 'PARACETAMOL + CAFEINE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 46,
                'nom_commercial' => 'THEINOL',
                'dci' => 'PARACETAMOL + CAFEINE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 47,
                'nom_commercial' => 'MIGRALGINE',
                'dci' => 'PARACETAMOL + CODEINE + CAFEINE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 48,
                'nom_commercial' => 'DYNAPAR',
                'dci' => 'PARACETAMOL + DICLOFENAC', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 49,
                'nom_commercial' => 'SOULADO PLUS',
                'dci' => 'PARACETAMOL + DICLOFENAC + CHLORZOXAZONE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 50,
                'nom_commercial' => 'BRUSTAN',
                'dci' => 'PARACETAMOL + IBUPROFENE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 51,
                'nom_commercial' => 'GENFORTE',
                'dci' => 'PARACETAMOL + IBUPROFENE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 52,
                'nom_commercial' => 'IBUMOL',
                'dci' => 'PARACETAMOL + IBUPROFENE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 53,
                'nom_commercial' => 'PROFENOL',
                'dci' => 'PARACETAMOL + IBUPROFENE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 54,
                'nom_commercial' => 'SOULADO',
                'dci' => 'PARACETAMOL + IBUPROFENE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 55,
                'nom_commercial' => 'TRIALGIC',
                'dci' => 'PARACETAMOL + IBUPROFENE + CAFEINE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 56,
                'nom_commercial' => 'LAMALINE',
                'dci' => 'PARACETAMOL + OPIUM', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 57,
                'nom_commercial' => 'IXPRIM',
                'dci' => 'PARACETAMOL + TRAMADOL', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 58,
                'nom_commercial' => 'ZALDIAR',
                'dci' => 'PARACETAMOL + TRAMADOL', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 59,
                'nom_commercial' => 'TRABAR',
                'dci' => 'TRAMADOL', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 60,
                'nom_commercial' => 'TRAMADIS',
                'dci' => 'TRAMADOL', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 61,
                'nom_commercial' => 'CONTRAMAL',
                'dci' => 'TRAMADOL', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 62,
                'nom_commercial' => 'TOPALGIC',
                'dci' => 'TRAMADOL', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 63,
                'nom_commercial' => 'ZAMUDOL',
                'dci' => 'TRAMADOL', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 64,
                'nom_commercial' => 'RAPIFEN',
                'dci' => 'ALFENTANYL', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 65,
                'nom_commercial' => 'DUROGESIC',
                'dci' => 'FENTANYL', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 66,
                'nom_commercial' => 'FENTANYL JANSSEN',
                'dci' => 'FENTANYL', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 67,
                'nom_commercial' => 'ACTISKENAN',
                'dci' => 'MORPHINE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 68,
                'nom_commercial' => 'MOSCONTIN',
                'dci' => 'MORPHINE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 69,
                'nom_commercial' => 'ORAMORPH',
                'dci' => 'MORPHINE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 70,
                'nom_commercial' => 'SUFENTA',
                'dci' => 'SUFENTANYL', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 71,
                'nom_commercial' => 'SUFENTANYL',
                'dci' => 'SUFENTANYL', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 72,
                'nom_commercial' => 'MORPHINE',
                'dci' => 'SULFATE DE MORPHINE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 73,
                'nom_commercial' => 'SKENAN',
                'dci' => 'SULFATE DE MORPHINE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 74,
                'nom_commercial' => 'MARCAÏNE',
                'dci' => 'BUPIVACAÏNE CHLORHYDRATE MONOHYDRAT', 
                'taux_rem' => 0.5,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 75,
                'nom_commercial' => 'SCANDICAÏNE',
                'dci' => 'CHLORHYDRATE DE MEPIVACAÏNE', 
                'taux_rem' => 0.5,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 76,
                'nom_commercial' => 'EMLA',
                'dci' => 'LIDOCAÏNE', 
                'taux_rem' => 0.5,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 77,
                'nom_commercial' => 'XYLOCAÏNE',
                'dci' => 'LIDOCAÏNE', 
                'taux_rem' => 0.5,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 78,
                'nom_commercial' => 'XYLOCAÏNE ADRENALINE',
                'dci' => 'LIDOCAÏNE + ADRENALINE', 
                'taux_rem' => 0.5,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 79,
                'nom_commercial' => 'XYLOCAÏNE NAPHAZOLINE',
                'dci' => 'XYLOCAÏNE + NAPHAZOLINE', 
                'taux_rem' => 0.5,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 80,
                'nom_commercial' => 'SPECIAFOLDINE',
                'dci' => 'ACIDE FOLIQUE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 81,
                'nom_commercial' => 'ACFOL',
                'dci' => 'ACIDE FOLIQUE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 82,
                'nom_commercial' => 'RANFERON',
                'dci' => 'ACIDE FOLIQUE + FER', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 83,
                'nom_commercial' => 'FERCEFOL',
                'dci' => 'ACIDE FOLIQUE + FER', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 84,
                'nom_commercial' => 'FOLIFER',
                'dci' => 'ACIDE FOLIQUE + FER', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 85,
                'nom_commercial' => 'FEROZYN',
                'dci' => 'ACIDE FOLIQUE + FER + VIT B12', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 86,
                'nom_commercial' => 'FER UCB',
                'dci' => 'FER', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 87,
                'nom_commercial' => 'VENOFER',
                'dci' => 'FER', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 88,
                'nom_commercial' => 'FERROSTRANE',
                'dci' => 'FER', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 89,
                'nom_commercial' => 'FUMAFER',
                'dci' => 'FER', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 90,
                'nom_commercial' => 'TARDYFERON',
                'dci' => 'FER', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 91,
                'nom_commercial' => 'HAEMUP',
                'dci' => 'FER + ACIDE FOLIQUE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 92,
                'nom_commercial' => 'TARDYFERON B9',
                'dci' => 'FER + ACIDE FOLIQUE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 93,
                'nom_commercial' => 'FEFOL',
                'dci' => 'FER + ACIDE FOLIQUE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 94,
                'nom_commercial' => 'AMIFER',
                'dci' => 'FER + ACIDE FOLIQUE + VIT B12', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 95,
                'nom_commercial' => 'BIOFER 12',
                'dci' => 'FER + ACIDE FOLIQUE + VIT B12', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 96,
                'nom_commercial' => 'BIOFERON',
                'dci' => 'FER + ACIDE FOLIQUE + VIT B12', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 97,
                'nom_commercial' => 'GYNOFER B12',
                'dci' => 'FER + ACIDE FOLIQUE + VIT B12', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 98,
                'nom_commercial' => 'FERRAVIT',
                'dci' => 'FER + ACIDE FOLIQUE + VIT B12 + ZINC', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 99,
                'nom_commercial' => 'IVEFERAN',
                'dci' => 'FER SUCROSE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 100,
                'nom_commercial' => 'ENCIFER',
                'dci' => 'HYDROXYDE FERRIQUE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 101,
                'nom_commercial' => 'ELVORINE',
                'dci' => 'HLEVOFOLINATE DE CALCIUM', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 102,
                'nom_commercial' => 'ACOFAN',
                'dci' => 'ACECLOFENAC', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 103,
                'nom_commercial' => 'AIRTAL',
                'dci' => 'ACECLOFENAC', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 104,
                'nom_commercial' => 'ZERODOL',
                'dci' => 'ACECLOFENAC', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 105,
                'nom_commercial' => 'ACTINAC PLUS',
                'dci' => 'ACECLOFENAC + PARACETAMOL', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 106,
                'nom_commercial' => 'PONSTYL',
                'dci' => 'ACIDE MEFENAMIQUE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 107,
                'nom_commercial' => 'NIFLUGEL',
                'dci' => 'ACIDE NIFLUMIQUE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 108,
                'nom_commercial' => 'NIFLUGEL',
                'dci' => 'ACIDE NIFLUMIQUE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 109,
                'nom_commercial' => 'NIFLURIL',
                'dci' => 'ACIDE NIFLUMIQUE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 110,
                'nom_commercial' => 'FLANID GE',
                'dci' => 'ACIDE TIAPROFENIQUE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 111,
                'nom_commercial' => 'SURGAM',
                'dci' => 'ACIDE TIAPROFENIQUE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 112,
                'nom_commercial' => 'TIAFEN',
                'dci' => 'ACIDE TIAPROFENIQUE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 113,
                'nom_commercial' => 'TIAPRIDAL',
                'dci' => 'ATIAPRIDE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
            [
                'id' => 114,
                'nom_commercial' => 'TIBERAL',
                'dci' => 'ORNIDAZOLE', 
                'taux_rem' => 0.8,
                'posologie' => '',
                'effet_indesir' => '',
                'indication' => '',
                'contre_indi' => '',
                'grossesse_allait' => '',
                'seen' => 0,
                'statut' => 1,
                
            ],
        ]);
    }
}